name: Build Firmware

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up ARM GCC Toolchain # Install arm-none-eabi-gcc
      run: |
        wget -O toolchain.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
        tar -xf toolchain.tar.xz
        export PATH=$PATH:$(pwd)/gcc-arm-none-eabi-13.2/bin
    
    - name: Build Firmware
      run: |
        make build 2>&1 | tee build.log
        if grep -q "warning" build.log; then
          echo "Build failed due to warnings."
          exit 1
        fi
      
    - name: Upload Firmware
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: firmware.bin
