name: Build Firmware

on:
  pull_request:
    branches:
      - main
      - CI/CD
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Firmware
        run: |
          wget -O toolchain.tar.xz https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz
          tar -xf toolchain.tar.xz
          export PATH=$PATH:$(pwd)/arm-gnu-toolchain-13.2.Rel1-x86_64-arm-none-eabi/bin
          
          make build 2>&1 | tee build.log
          warning_count=$(grep -c "warning" build.log)
          if [ "$warning_count" -gt 1 ]; then
            echo "Build failed due to multiple warnings."
            exit 1
          fi
        
      - name: Upload Firmware
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: firmware.bin
